### ISSUE TITLE
Špatně generovaný texyla.js

### ISSUE THREAD

**Issue by adamtomecek** [janmarek/Texyla#1]
V TexylaLoaderu je "špatně" nadefinovaná cesta k souborům, což způsobovalo neplatné adresy k obrázkům Texyly. Nevím proč, ale místo adresy na složku mého projektu (v mém případě localhost/cms/document_root...) se generovala adresa localhost/texyla52/document_root. netuším, kde je chyba a tak jsem sprostě nahradil jeden řádek v TexylaLoaderu a vše běhá jak má.

//$this->sourceUri = Environment::getVariable("baseUri") . "texyla";
$this->sourceUri = WWW_DIR . "/texyla";

**Comment by janmarek** [comment]
smaž si obsah složky webtemp

**Comment by adamtomecek** [comment]
To jsem samozřejmě několikrát zkoušel. Pak jsem přepsal tento řádek, smazal webtemp a už všechno funguje. A omlouvám se, že to píšu přímo k Texyle a ne k Nette + Texyla.
