### ISSUE TITLE
jQuery("head script:last").attr("src") is undefined

### ISSUE THREAD

**Issue by Lopo** [janmarek/Texyla#13]
v texyla.js riadok 121
nastava v pripade ze v headeri neni posledny script linkovaci, tj u mna ked je to priamo zapisany kod (WebLoader + head.js linkovanie)
nepomoze ani ked baseDir nastavim v options kedze riadok 121 sa vykonava este pred zavolanim samotnej texyly

riesenie ma aktualne nenapada

**Comment by janmarek** [comment]
možná tam dát nějakou podmínku, že když $('head script:last').size() === 0, tak nastav null

**Comment by voda** [comment]
nepomohlo by `jQuery("head script[src]:last").attr("src")`?

**Comment by Lopo** [comment]
mno obecne myslim ze nejake zistovanie takeho atributu z hlavicky je chyba ... pretoze v hlavicke mozu byt uplne ine skripty, ktore nemosia mat s texylou absolutne nic spolocne - alebo mozu byt tahane z CDN pricom texyla z lokalu

ja som teraz ten riadok 121 zakomentoval a do vstupnych options som dal ako jeden z parametrov ten adresar a ide mi to bez chyby - takze momentalne asi jedine funkcne riesenie je tu automatiku odstavit a brat ten parameter z options, tj mat ho ako povinny

**Comment by janmarek** [comment]
souhlas.
