### ISSUE TITLE
Uncaught TypeError: Cannot call method 'replace' of null

### ISSUE THREAD

**Issue by josefsabl** [janmarek/Texyla#18]
I followed "Základy implementace" yet, I get this error.
# Stack:

Uncaught TypeError: Cannot call method 'replace' of null
Texyla.expandtexyla.js:56
Texylatexyla.js:40
(anonymous function)texyla.js:5
e.extend.eachjquery.min.js:2
e.fn.e.eachjquery.min.js:2
jQuery.fn.extend.texylatexyla.js:4
(anonymous function)jquery.setup.js:3
f.Callbacks.njquery.min.js:2
f.Callbacks.o.fireWithjquery.min.js:2
e.extend.readyjquery.min.js:2
c.addEventListener.Bjquery.min.js:2

**Comment by ondrejmirtes** [comment]
+1

**Comment by janmarek** [comment]
Souvisí s #13 a pak je ještě potřeba nastavit veškeré cesty, co kde může texyla vyžadovat - tj. previewPath a cesty od files pluginu.

**Comment by janmarek** [comment]
viz #24
